# Test configuration for .adorevrc.yaml support
gemini:
  defaultModel: "gemini-2.0-flash-lite"
  temperature: 0.2

logging:
  level: "debug"
  console:
    colors: true
    timestamps: true

review:
  severityThreshold: "info"
  format: "table"
  maxTableFindings: 15