# Example .adorevrc.yaml configuration file
# Copy this file to .adorevrc.yaml in your project root and customize as needed

# Global LLM settings
llm:
  # Default provider: gemini-api | openai | openrouter
  defaultProvider: gemini-api

# Gemini AI Configuration
gemini:
  defaultModel: "gemini-1.5-pro-002"
  temperature: 0.1
  topP: 0.95
  topK: 40
  timeout: 60000

# OpenAI Configuration (optional)
openai:
  defaultModel: "gpt-4o-mini"
  timeout: 120000

# OpenRouter Configuration (optional)
openrouter:
  defaultModel: "openai/gpt-4o-mini"
  timeout: 120000

# Rate Limiting Configuration
rateLimit:
  batchSize: 3
  sleepMs: 2000
  maxConcurrent: 2
  backoffMultiplier: 2.0
  maxBackoffMs: 30000

# Review Configuration
review:
  severityThreshold: "info"
  format: "table"
  maxTableFindings: 20
  maxDiffLineLength: 120
  contextLines: 3

# File Processing Configuration
files:
  defaultInclude:
    - "**/*.ts"
    - "**/*.js"
    - "**/*.tsx"
    - "**/*.jsx"
    - "**/*.py"
    - "**/*.java"
    - "**/*.cs"
    - "**/*.cpp"
    - "**/*.c"
    - "**/*.h"
  defaultExclude:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "*.min.js"
    - "*.bundle.js"
  maxFileSize: 1048576  # 1MB
  maxTotalFiles: 100

# Logging Configuration
logging:
  level: "info"
  file:
    enabled: true
    path: "./logs/ado-review.log"
    maxSize: 10485760  # 10MB
    maxFiles: 5
  console:
    enabled: true
    colors: true
    timestamps: true
  maskSecrets:
    - "AZURE_DEVOPS_TOKEN"
    - "GEMINI_API_KEY"

# Comments Configuration
comments:
  maxCommentsPerPR: 50
  maxCommentLength: 2000
  idempotent: true
  template: "🤖 **AI Code Review**\n\n{findings}\n\n---\n*Generated by ado-review*"

# Status Configuration
status:
  context: "ado-review/ai-analysis"
  descriptions:
    pending: "AI code review in progress..."
    success: "AI code review completed successfully"
    failed: "AI code review found issues"
    error: "AI code review encountered an error"
  targetUrl: null

# Git Configuration
git:
  depth: 100
  timeout: 30000
  excludePatterns:
    - "*.lock"
    - "package-lock.json"
    - "yarn.lock"
    - "*.log"

# Azure DevOps Configuration
azo:
  timeout: 30000
  maxRetries: 3
  retryDelay: 1000
  apiVersion: "7.1-preview.1"
